env_file: .env

app:
    host: "localhost"
    port: 8000

database:
    driver: "postgresql+asyncpg"
    name: "visionero"

logger:
  sink: "visionero.log"
  format: "{time}\t|\t{level}\t|\t{message}"
  level: "DEBUG"
  rotation: "10MB"
  compression: "zip"

origins:
  - "*"